# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PARSE_FIT <- function(f1) {
    .Call('elpatron_PARSE_FIT', PACKAGE = 'elpatron', f1)
}

DIFF <- function(x) {
    .Call('elpatron_DIFF', PACKAGE = 'elpatron', x)
}

CUMSUM <- function(x) {
    .Call('elpatron_CUMSUM', PACKAGE = 'elpatron', x)
}

EMA_WEIGHTS <- function(len) {
    .Call('elpatron_EMA_WEIGHTS', PACKAGE = 'elpatron', len)
}

ROLLMEAN <- function(x, window, na_rm, ema) {
    .Call('elpatron_ROLLMEAN', PACKAGE = 'elpatron', x, window, na_rm, ema)
}

ROLLMEAN_TIME <- function(x, time, window, na_rm) {
    .Call('elpatron_ROLLMEAN_TIME', PACKAGE = 'elpatron', x, time, window, na_rm)
}

WEXPEND <- function(t, P, CP) {
    .Call('elpatron_WEXPEND', PACKAGE = 'elpatron', t, P, CP)
}

PARSE_PWX <- function(file_path) {
    .Call('elpatron_PARSE_PWX', PACKAGE = 'elpatron', file_path)
}

PWX_START_TIME <- function(file_path) {
    .Call('elpatron_PWX_START_TIME', PACKAGE = 'elpatron', file_path)
}

PARSE_TCX <- function(file_path) {
    .Call('elpatron_PARSE_TCX', PACKAGE = 'elpatron', file_path)
}

TCX_LAPS <- function(file_path) {
    .Call('elpatron_TCX_LAPS', PACKAGE = 'elpatron', file_path)
}

PARSE_GPX <- function(file_path) {
    .Call('elpatron_PARSE_GPX', PACKAGE = 'elpatron', file_path)
}

